// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-p-z5bPoK4lfPlZx_PTGC86jx7TSpgZk',
    appId: '1:364173555596:web:4b0956f576f907cfb148a9',
    messagingSenderId: '364173555596',
    projectId: 'profileapp-80e3a',
    authDomain: 'profileapp-80e3a.firebaseapp.com',
    storageBucket: 'profileapp-80e3a.appspot.com',
    measurementId: 'G-G59FWG8C3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWhTVgUzd0CgzGlQya7Yx76lLVwf6FhCg',
    appId: '1:364173555596:android:0674ce8bb6b7c212b148a9',
    messagingSenderId: '364173555596',
    projectId: 'profileapp-80e3a',
    storageBucket: 'profileapp-80e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcP9pu9Z0g0gO7vMhM6b3qugGjEwhru0s',
    appId: '1:364173555596:ios:c08f0a918628e329b148a9',
    messagingSenderId: '364173555596',
    projectId: 'profileapp-80e3a',
    storageBucket: 'profileapp-80e3a.appspot.com',
    iosBundleId: 'com.example.profileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcP9pu9Z0g0gO7vMhM6b3qugGjEwhru0s',
    appId: '1:364173555596:ios:2532f48d6b9343a4b148a9',
    messagingSenderId: '364173555596',
    projectId: 'profileapp-80e3a',
    storageBucket: 'profileapp-80e3a.appspot.com',
    iosBundleId: 'com.example.profileApp.RunnerTests',
  );
}
